modLoader="javafml"
loaderVersion="[43,)"
license="GPLv3"

[[mods]]
modId="simplemusket"
version="${file.jarVersion}"
displayName="Simple Musket"
logoFile="simplemusket.png"
credits="BrokenKeyboard, ewewukek"
authors="BrokenKeyboard"
description='''Adds a musket and four types of ammo to Minecraft.'''

[[dependencies.simplemusket]]
modId="forge"
mandatory=true
versionRange="[43.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.simplemusket]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2]"
ordering="NONE"
side="BOTH"