modLoader="javafml"
loaderVersion="${loader_version_range}"
license="GPLv3"

[[mods]]
modId="simplemusket"
version="${file.jarVersion}"
displayName="Simple Musket"
logoFile="simplemusket.png"
credits="BrokenKeyboard, ewewukek"
authors="BrokenKeyboard"
description='''Adds a musket and four types of ammo to Minecraft.'''

[[dependencies.simplemusket]]
modId="forge"
mandatory=true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.simplemusket]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"