@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.brokenkeyboard.simplemusket.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;