@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.brokenkeyboard.simplemusket.enchantment;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;