@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.brokenkeyboard.simplemusket;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;