@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.brokenkeyboard.simplemusket.item;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;